import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class CubeStackingGame
{
	public int MaximumValue(int n, int[] c1, int[] c2, int[] c3, int[] c4)
	{
		int cf1[][] = new int[][] {c1, c2, c3, c4};
		int[] c5 = Arrays.copyOf(c1,n);
		int[] c6 = Arrays.copyOf(c4,n);
		int[] c7 = Arrays.copyOf(c3,n);
		int[] c8 = Arrays.copyOf(c2,n);
		int cf2[][] = new int[][] {c5, c6, c7, c8};
		int c[][][] = new int[][][]{cf1, cf2};
		boolean b1[] = new boolean[n+1];
		boolean b2[] = new boolean[n+1];
		boolean b3[] = new boolean[n+1];
		boolean b4[] = new boolean[n+1];
		boolean b[][] = new boolean[][]{b1, b2, b3, b4};

		b1[c1[0]] = true;
		b2[c2[0]] = true;
		b3[c3[0]] = true;
		b4[c4[0]] = true;

		return getMaxValue(1, c, b) + 1;
	}

	private int getMaxValue(int i, int[][][] colors, boolean[][] b) {
		if(i == colors[0][0].length) return 0;

		int max = 0;
		for (int l = 0; l < 2; l++) {
			int c[][] = colors[l];
			for (int j = 0; j < 4; j++) {
				boolean isValid = true;
				for (int k = 0; k < 4; k++) {
					int p = (j + k) % 4;
					if (b[k][c[p][i]]) isValid = false;
				}
				if (isValid) {
					for (int k = 0; k < 4; k++) {
						int p = (j + k) % 4;
						b[k][c[p][i]] = true;
					}
					max = Math.max(getMaxValue(i + 1, colors, b) + 1, max);
					for (int k = 0; k < 4; k++) {
						int p = (j + k) % 4;
						b[k][c[p][i]] = false;
					}
				}
			}
		}

		return max;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int[] p1, int[] p2, int[] p3, int[] p4, boolean hasAnswer, int p5) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p3.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p3[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p4.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p4[i]);
		}
		System.out.print("}");
		System.out.println("]");
		CubeStackingGame obj;
		int answer;
		obj = new CubeStackingGame();
		long startTime = System.currentTimeMillis();
		answer = obj.MaximumValue(p0, p1, p2, p3, p4);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p5);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p5;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int[] p1;
		int[] p2;
		int[] p3;
		int[] p4;
		int p5;
		
		// ----- test 0 -----
		p0 = 2;
		p1 = new int[]{1,1};
		p2 = new int[]{2,1};
		p3 = new int[]{1,2};
		p4 = new int[]{2,2};
		p5 = 1;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 2;
		p1 = new int[]{1,2};
		p2 = new int[]{1,2};
		p3 = new int[]{1,2};
		p4 = new int[]{1,2};
		p5 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 2;
		p1 = new int[]{1,1};
		p2 = new int[]{1,2};
		p3 = new int[]{1,2};
		p4 = new int[]{1,2};
		p5 = 1;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 2;
		p1 = new int[]{1,1};
		p2 = new int[]{2,2};
		p3 = new int[]{1,1};
		p4 = new int[]{2,2};
		p5 = 2;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 2;
		p1 = new int[]{1,1};
		p2 = new int[]{1,2};
		p3 = new int[]{2,2};
		p4 = new int[]{2,1};
		p5 = 2;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = 4;
		p1 = new int[]{1,1,3,4};
		p2 = new int[]{1,2,3,4};
		p3 = new int[]{1,3,3,4};
		p4 = new int[]{1,4,3,4};
		p5 = 1;
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = 4;
		p1 = new int[]{1,1,1,1};
		p2 = new int[]{2,2,2,4};
		p3 = new int[]{3,3,3,3};
		p4 = new int[]{4,4,4,2};
		p5 = 4;
		all_right = KawigiEdit_RunTest(6, p0, p1, p2, p3, p4, true, p5) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
