import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class ForumPostMedium
{
	public String getShownPostTime(String currentTime, String exactPostTime)
	{
        String[] splits = exactPostTime.split(":");
        int time[] = new int[]{Integer.valueOf(splits[0]),Integer.valueOf(splits[1]),Integer.valueOf(splits[2])};
        String[] splits2 = currentTime.split(":");
        currentTime = Integer.valueOf(splits2[0])+":"+Integer.valueOf(splits2[1])+":"+Integer.valueOf(splits2[2]);
        exactPostTime = Integer.valueOf(splits[0])+":"+Integer.valueOf(splits[1])+":"+Integer.valueOf(splits[2]);
        int count = 0;
        while (!exactPostTime.equals(currentTime)) {
            time[2] = (time[2] + 1) % 60;
            if(time[2] == 0) {
                time[1] = (time[1] + 1) % 60;
                if(time[1] == 0) {
                    time[0] = (time[0] + 1) % 24;
                }
            }
            exactPostTime = time[0] + ":" + time[1] + ":" + time[2];
            count++;
        }

        if(count < 60) return "few seconds ago";
        if(count < 3600) return (count / 60) + " minutes ago";
        return (count / 3600) + " hours ago";		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, String p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "\"" + p1 + "\"");
		System.out.println("]");
		ForumPostMedium obj;
		String answer;
		obj = new ForumPostMedium();
		long startTime = System.currentTimeMillis();
		answer = obj.getShownPostTime(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		String p1;
		String p2;
		
		// ----- test 0 -----
		p0 = "12:12:12";
		p1 = "12:11:13";
		p2 = "few seconds ago";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "12:12:12";
		p1 = "11:12:12";
		p2 = "1 hours ago";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "12:12:12";
		p1 = "11:12:13";
		p2 = "59 minutes ago";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "12:12:12";
		p1 = "12:12:13";
		p2 = "23 hours ago";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
