import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class Sherlock
{
	public String isItHim(String firstName, String lastName)
	{
		String FALSE = "It is someone else";
		String TRUE = "It is him";

		if(firstName.length() < 7 || lastName.length() < 7) return FALSE;
		if(firstName.charAt(0) != 'B' || lastName.charAt(0) != 'C') return FALSE;
		int c1 = 0;
		for (int i = 0; i < firstName.length(); i++) {
			if("BENEDICT".contains(firstName.charAt(i) + "")) {
				c1++;
			}
		}
		int c2 = 0;
		for (int i = 0; i < lastName.length(); i++) {
			if("CUMBERBATCH".contains(lastName.charAt(i) + "")) {
				c2++;
			}
		}
		if(c1 < 3 || c2 < 5) return FALSE;

		return TRUE;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, String p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "\"" + p1 + "\"");
		System.out.println("]");
		Sherlock obj;
		String answer;
		obj = new Sherlock();
		long startTime = System.currentTimeMillis();
		answer = obj.isItHim(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		String p1;
		String p2;
		
		// ----- test 0 -----
		p0 = "BENEDICT";
		p1 = "CUMBERBATCH";
		p2 = "It is him";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "BENADRYL";
		p1 = "CUCUMBERPATCH";
		p2 = "It is him";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "HARSHIT";
		p1 = "MEHTA";
		p2 = "It is someone else";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "BATAXXAT";
		p1 = "CURMUDGEON";
		p2 = "It is him";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "BENEDI";
		p1 = "CUMBER";
		p2 = "It is someone else";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = "BAXAXAXY";
		p1 = "CENTRIFUGAL";
		p2 = "It is someone else";
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = "BUMBLESHACK";
		p1 = "CRUMPLEHORN";
		p2 = "It is him";
		all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
