import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class SixteenQueens
{
	public int[] addQueens(int[] row, int[] col, int add)
	{
		boolean isCol[] = new boolean[50];
		boolean isRow[] = new boolean[50];
		int idx = 0;
		for (int i = 0; i < row.length; i++) {
			isRow[row[i]] = true;
			isCol[col[i]] = true;
		}
        int ans[] = new int[add * 2];
        for (int i = 0; i < 50; i++) {
            for (int j = 0; j < 50; j++) {
                boolean isValid = true;
                if(isRow[i] || isCol[j]) {
                    isValid = false;
                }
                for (int k = 0; k < row.length; k++) {
                    if(Math.abs(row[k] - i) == Math.abs(col[k] - j)) {
                        isValid = false;
                        break;
                    }
                }
                for (int k = 0; k < idx; k += 2) {
                    if(Math.abs(ans[k] - i) == Math.abs(ans[k + 1] - j)) {
                        isValid = false;
                        break;
                    }
                }
                if(isValid && idx < add * 2) {
                    ans[idx] = i;
                    ans[idx + 1] = j;
                    idx += 2;
                    isRow[i] = true;
                    isCol[j] = true;
                }
            }
        }

        return ans;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, int p2, boolean hasAnswer, int[] p3) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + p2);
		System.out.println("]");
		SixteenQueens obj;
		int[] answer;
		obj = new SixteenQueens();
		long startTime = System.currentTimeMillis();
		answer = obj.addQueens(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p3.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print(p3[i]);
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(answer[i]);
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p3.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (answer[i] != p3[i]) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		int p2;
		int[] p3;
		
		// ----- test 0 -----
		p0 = new int[]{3};
		p1 = new int[]{5};
		p2 = 1;
		p3 = new int[]{0,0};
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{0};
		p1 = new int[]{1};
		p2 = 1;
		p3 = new int[]{4,7};
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{0};
		p1 = new int[]{1};
		p2 = 3;
		p3 = new int[]{4,7,15,0,49,49};
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{14,19};
		p1 = new int[]{3,47};
		p2 = 0;
		p3 = new int[]{};
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{};
		p1 = new int[]{};
		p2 = 2;
		p3 = new int[]{0,0,1,2};
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new int[]{1,2,3};
		p1 = new int[]{7,2,19};
		p2 = 1;
		p3 = new int[]{0,1};
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
