import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class VisitN
{
	public String visit(int n, int r, int c)
	{
		char b[][] = new char[30][30];
		StringBuilder sb = new StringBuilder();
		b[r][c] = '.';
		n--;
		while (r != 0 && n > 0) {
			r--;
			n--;
			b[r][c] = '.';
			sb.append('N');
		}
		while (c != 0 && n > 0) {
			c--;
			b[r][c] = '.';
			n--;
			sb.append('W');
		}
		for (int i = 0; i < 15; i++) {
			for (int j = 0; j < 30 && n > 0; j++) {
				r++;
				if(b[r][c] != '.') {
					n--;
					b[r][c] = '.';
				}
				sb.append('S');
			}
			if(n > 0) {
				c++;
				if(b[r][c] != '.') {
					n--;
					b[r][c] = '.';
				}
				sb.append('E');
			}
			for (int j = 0; j < 30 && n > 0; j++) {
				r--;
				if(b[r][c] != '.') {
					n--;
					b[r][c] = '.';
				}
				sb.append('N');
			}
			if(n > 0 && i < 14) {
				c++;
				if(b[r][c] != '.') {
					n--;
					b[r][c] = '.';
				}
				sb.append('E');
			}
		}
		return sb.toString();
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, boolean hasAnswer, String p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + p2);
		System.out.println("]");
		VisitN obj;
		String answer;
		obj = new VisitN();
		long startTime = System.currentTimeMillis();
		answer = obj.visit(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p3 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p3);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		int p2;
		String p3;
		
		// ----- test 0 -----
		p0 = 1;
		p1 = 4;
		p2 = 7;
		p3 = "";
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 2;
		p1 = 4;
		p2 = 7;
		p3 = "N";
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 2;
		p1 = 0;
		p2 = 17;
		p3 = "W";
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 4;
		p1 = 1;
		p2 = 1;
		p3 = "NWEE";
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 10;
		p1 = 5;
		p2 = 13;
		p3 = "NWSSEENNSSWS";
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
