import java.util.*;


public class Yllion
{
	public String getPower(String a, String b)
	{
	    String powers[] = new String[]{"ten", "hundred", "myriad", "myllion", "byllion", "tryllion", "quadryllion", "quintyllion", "sextyllion", "septyllion", "octyllion", "nonyllion", "decyllion"};
		Map<String, Integer> m = new HashMap<String, Integer>(){{
			put("one", 0);
			put("ten", 1);
			put("hundred", 1<<1);
			put("myriad", 1<<2);
			put("myllion", 1<<3);
			put("byllion", 1<<4);
			put("tryllion", 1<<5);
			put("quadryllion", 1<<6);
			put("quintyllion", 1<<7);
			put("sextyllion", 1<<8);
			put("septyllion", 1<<9);
			put("octyllion", 1<<10);
			put("nonyllion", 1<<11);
			put("decyllion", 1<<12);
		}};

		int product = getSum(a, m) + getSum(b, m);
		LinkedList<String> l = new LinkedList<>();
        for (int i = powers.length - 1; i >= 1; i--) {
            if((product&(1<<i)) > 0) {
                l.addFirst(powers[i]);
                product = product - (1<<i);
            }
        }
        String ans = "one";
        if(product == 1) ans = "ten";

        for (String v : l) {
            ans += " " + v;
        }

        return ans;
	}

    private int getSum(String s, Map<String, Integer> m) {
        String[] splits = s.split(" ");
        int sum = 0;

        for(String split : splits) {
            sum += m.get(split);
        }

        return sum;
    }

    // BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, String p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "\"" + p1 + "\"");
		System.out.println("]");
		Yllion obj;
		String answer;
		obj = new Yllion();
		long startTime = System.currentTimeMillis();
		answer = obj.getPower(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		String p1;
		String p2;
		
		// ----- test 0 -----
		p0 = "one";
		p1 = "one";
		p2 = "one";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "one";
		p1 = "ten";
		p2 = "ten";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "one hundred";
		p1 = "one hundred";
		p2 = "one myriad";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "ten hundred";
		p1 = "one hundred";
		p2 = "ten myriad";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "ten hundred myriad myllion";
		p1 = "one hundred myllion tryllion";
		p2 = "ten myllion byllion tryllion";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = "ten hundred myriad myllion byllion tryllion quadryllion quintyllion sextyllion septyllion octyllion nonyllion";
		p1 = "ten";
		p2 = "one decyllion";
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
